schema-version: v2
kind: action
metadata:
  name: commit-push-action
  display-name: commit-push-action
  description: test action
  version: 0.0.1
spec:
  type: shell
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  inputs: 
    - label: Commit message
      name: message
      type: text
    - label: Nome da Branch
      name: name_branch
      type: text
  shell:
    workdir: .
    equirements-check:
      - check-command:
          linux: |
            git --version
          
        info: "Git not installed"
    script:
      linux: |
        git add .
        git commit -m "{{message}}"
        git push origin {{name_branch}} 
        
      
