schema-version: v2
kind: action
metadata:
  name: commit-push-action
  display-name: commit-push-action
  description: test action
  version: 0.0.1
spec:
  type: shell
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  inputs: 
    - label: Personal Access Token
      name: pat
      type: password
    - label: Organization Name
      name: org_name
      type: text
    - label: Repository Name
      name: repo_name
      type: text
    - label: Commit message
      name: message
      type: text  
    - label: Branch
      name: branch_name
      type: text    
  shell:
    workdir: .
    requirements-check:
      - check-command:
          linux: |
            git --version            
          mac: |
            git --version
          windows: |
            git --version
        info: "Git not installed"    
    script:
      linux: |  
        git add .
        git commit -m "{{message}}"               
        git push https://{{pat}}@github.com/{{org_name}}/{{repo_name}}         
      mac: |
        git add .
        git commit -m "{{message}}" 
        git push https://{{pat}}@github.com/{{org_name}}/{{repo_name}} 
      windows: |
        git add .
        git commit -m "{{message}}" 
        git push https://{{pat}}@github.com/{{org_name}}/{{repo_name}} 
       
         
        
      
